import { SentryIssue } from "./sentry.js";
import { createBranch, commitFileFix, openPullRequest, getFileContent } from "./github.js";
import { analyzeBugAndFix } from "./claude.js";
import { notifySlack } from "./slack.js";
import { McpBridge } from "./mcp.js";
import { config } from "./config.js";
import { logger } from "./logger.js";

// ---- Types ----------------------------------------------------------------

export interface AgentResult {
  issueId: string;
  shortId: string;
  success: boolean;
  prUrl?: string;
  reason?: string;
}

// ---- Main Orchestrator ----------------------------------------------------

/**
 * Full pipeline for a single Sentry issue (MCP-powered):
 * 1. Claude actively investigates the issue via Sentry MCP tools
 * 2. Claude fetches the relevant source file from GitHub via tool call
 * 3. Claude returns a structured JSON fix
 * 4. We create a branch, commit the fix, and open a GitHub PR
 * 5. Notify Slack
 *
 * The key difference vs the old approach: Claude drives step 1 & 2 itself.
 * We only handle the git operations (steps 4-5).
 */
export async function solveIssue(
  issue: SentryIssue,
  mcp: McpBridge
): Promise<AgentResult> {
  logger.info(`\n${"─".repeat(60)}`);
  logger.info(`Processing: [${issue.shortId}] ${issue.title}`);
  logger.info(`Culprit: ${issue.culprit} | Events: ${issue.count}`);

  // ---- DRY RUN mode --------------------------------------------------------
  if (config.bot.dryRun) {
    logger.info(`[DRY RUN] Skipping real API calls for ${issue.shortId}`);
    return {
      issueId: issue.id,
      shortId: issue.shortId,
      success: true,
      prUrl: "https://github.com/dry-run/pr/0",
    };
  }

  try {
    // Step 1-3: Claude investigates via MCP + fetches files + generates fix
    const fix = await analyzeBugAndFix(issue, mcp);

    if (!fix) {
      const reason = "Claude could not generate a fix for this issue";
      logger.warn(`[${issue.shortId}] ${reason}`);
      await notifySlack({
        issueShortId: issue.shortId,
        issueTitle: issue.title,
        sentryPermalink: issue.permalink,
        prUrl: "",
        prNumber: 0,
        explanation: "",
        filePath: "",
        success: false,
        errorReason: reason,
      });
      return { issueId: issue.id, shortId: issue.shortId, success: false, reason };
    }

    logger.info(`[${issue.shortId}] Fix generated for: ${fix.filePath}`);

    // Step 4: Get the current SHA of the file (needed for the GitHub API commit)
    const existingFile = await getFileContent(fix.filePath);
    const fileSha = existingFile?.sha;

    // Step 5: Create branch and commit
    const branchName = `fix/sentry-${issue.shortId.toLowerCase()}`;
    await createBranch(branchName);
    await commitFileFix(
      branchName,
      fix.filePath,
      fix.fixedCode,
      fix.commitMessage,
      fileSha
    );

    // Step 6: Open PR
    const prBody = buildPrBody(issue, fix);
    const pr = await openPullRequest(branchName, `fix: ${issue.title}`, prBody);

    // Step 7: Notify Slack
    await notifySlack({
      issueShortId: issue.shortId,
      issueTitle: issue.title,
      sentryPermalink: issue.permalink,
      prUrl: pr.url,
      prNumber: pr.number,
      explanation: fix.explanation,
      filePath: fix.filePath,
      success: true,
    });

    logger.info(`[${issue.shortId}] ✅ PR opened: ${pr.url}`);
    return { issueId: issue.id, shortId: issue.shortId, success: true, prUrl: pr.url };

  } catch (err: unknown) {
    const reason = err instanceof Error ? err.message : String(err);
    logger.error(`[${issue.shortId}] ❌ Unexpected error`, { error: reason });
    return { issueId: issue.id, shortId: issue.shortId, success: false, reason };
  }
}

// ---- Helpers --------------------------------------------------------------

function buildPrBody(
  issue: SentryIssue,
  fix: { explanation: string; filePath: string }
): string {
  return [
    `## 🤖 Automated Fix by Bug Solver Bot`,
    ``,
    `This PR was automatically generated by an AI agent that deeply investigated a Sentry error using the Sentry MCP server.`,
    ``,
    `### Sentry Issue`,
    `- **ID:** [${issue.shortId}](${issue.permalink})`,
    `- **Error:** \`${issue.errorType}: ${issue.errorValue}\``,
    `- **Culprit:** \`${issue.culprit}\``,
    `- **Frequency:** ${issue.count} events`,
    ``,
    `### How This Fix Was Generated`,
    `1. Claude queried Sentry via MCP to get full event details and stack trace`,
    `2. Claude fetched the source file from GitHub`,
    `3. Claude identified the root cause and generated a minimal fix`,
    ``,
    `### Fix Summary`,
    `**File modified:** \`${fix.filePath}\``,
    ``,
    fix.explanation,
    ``,
    `---`,
    `> ⚠️ **Human review required.** Please verify this fix before merging.`,
    `> This PR was auto-generated by Bug Solver Bot powered by Claude + Sentry MCP.`,
  ].join("\n");
}
